pipeline {
    agent {
        label 'docker-agent'
    }
    stages {
        stage ('checkout') {
            steps {
                git url: 'https://github.com/kennethcdeguzman/calculator.git'
            }
        }
        stage ('build') {
            steps {
                sh 'cd calculator && ./gradlew compileJava'
            }
        }
        stage ('test') {
            steps {
                sh 'cd calculator && ./gradlew test'
            }
        }
        stage ('code coverage') {
            steps {
                sh 'cd calculator && ./gradlew test jacocoTestReport'
                publishHTML (target: [
                        reportDir: 'calculator/build/reports/jacoco/test/html',
                        reportFiles: 'index.html',
                        reportName: "JaCoCo Report"
                ])
                sh 'cd calculator && ./gradlew test jacocoTestCoverageVerification'
            }
        }
        stage ('package') {
            steps {
                sh 'cd calculator && ./gradlew build'
            }
        }
        stage ('docker build') {
            steps {
                sh 'cd calculator && docker build -t thekennymac/calculator .'
            }
        }
    }
    post {
        def messageColor = 'success'
        always {
            color = ${currentBuild.currentResult} == 'FAILURE' ? 'danger' : 'success'
            slackSend channel: '#jenkins', color: messageColor, message: "your pipeline ${currentBuild.fullDisplayName} has ${currentBuild.currentResult}"
        }
    }
}